/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author xp
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCalculadora
     */
    double operando1 = 0;//guarda el primer número que metamos
    String operacion = "";//guarda la operación pulsada
    public VentanaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        boton07 = new javax.swing.JButton();
        boton08 = new javax.swing.JButton();
        boton09 = new javax.swing.JButton();
        boton04 = new javax.swing.JButton();
        boton05 = new javax.swing.JButton();
        boton06 = new javax.swing.JButton();
        boton01 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton03 = new javax.swing.JButton();
        boton00 = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pantalla.setBackground(new java.awt.Color(0, 0, 0));
        pantalla.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        pantalla.setForeground(new java.awt.Color(0, 51, 255));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setText("0");
        pantalla.setOpaque(true);
        getContentPane().add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 355, 75));

        boton07.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton07.setText("7");
        boton07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton07ActionPerformed(evt);
            }
        });
        getContentPane().add(boton07, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, 64, 64));

        boton08.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton08.setText("8");
        boton08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton08ActionPerformed(evt);
            }
        });
        getContentPane().add(boton08, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 104, 64, 64));

        boton09.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton09.setText("9");
        boton09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton09ActionPerformed(evt);
            }
        });
        getContentPane().add(boton09, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 104, 64, 64));

        boton04.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton04.setText("4");
        boton04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton04ActionPerformed(evt);
            }
        });
        getContentPane().add(boton04, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, 64, 64));

        boton05.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton05.setText("5");
        boton05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton05ActionPerformed(evt);
            }
        });
        getContentPane().add(boton05, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 186, 64, 64));

        boton06.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton06.setText("6");
        boton06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton06ActionPerformed(evt);
            }
        });
        getContentPane().add(boton06, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 186, 64, 64));

        boton01.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton01.setText("1");
        boton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton01ActionPerformed(evt);
            }
        });
        getContentPane().add(boton01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 268, 64, 64));

        boton02.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton02.setText("2");
        boton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton02ActionPerformed(evt);
            }
        });
        getContentPane().add(boton02, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 268, 64, 64));

        boton03.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton03.setText("3");
        boton03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton03ActionPerformed(evt);
            }
        });
        getContentPane().add(boton03, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 268, 64, 64));

        boton00.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        boton00.setText("0");
        boton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton00ActionPerformed(evt);
            }
        });
        getContentPane().add(boton00, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 64, 64));

        suma.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        getContentPane().add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 105, 64, 64));

        igual.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        getContentPane().add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 350, 160, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton07ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("7");
        }else{
            pantalla.setText(auxiliar + "7");
        }
    }//GEN-LAST:event_boton07ActionPerformed
    
    private void boton08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton08ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("8");
        }else{
            pantalla.setText(auxiliar + "8");
        }
    }//GEN-LAST:event_boton08ActionPerformed

    private void boton09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton09ActionPerformed
                String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("9");
        }else{
            pantalla.setText(auxiliar + "9");
        }
    }//GEN-LAST:event_boton09ActionPerformed

    private void boton04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton04ActionPerformed
                String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("4");
        }else{
            pantalla.setText(auxiliar + "4");
        }
    }//GEN-LAST:event_boton04ActionPerformed

    private void boton05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton05ActionPerformed
                String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("5");
        }else{
            pantalla.setText(auxiliar + "5");
        }
    }//GEN-LAST:event_boton05ActionPerformed

    private void boton06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton06ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("6");
        }else{
            pantalla.setText(auxiliar + "6");
        }
    }//GEN-LAST:event_boton06ActionPerformed

    private void boton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton01ActionPerformed
                String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("1");
        }else{
            pantalla.setText(auxiliar + "1");
        }
    }//GEN-LAST:event_boton01ActionPerformed

    private void boton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton02ActionPerformed
                String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("2");
        }else{
            pantalla.setText(auxiliar + "2");
        }
    }//GEN-LAST:event_boton02ActionPerformed

    private void boton03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton03ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("3");
        }else{
            pantalla.setText(auxiliar + "3");
        }
    }//GEN-LAST:event_boton03ActionPerformed

    private void boton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton00ActionPerformed
        String auxiliar = pantalla.getText();
        if(auxiliar.equals("0")){
            pantalla.setText("0");
        }else{
            pantalla.setText(auxiliar + "0");
        }
    }//GEN-LAST:event_boton00ActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        operacion = "+";
        //Double.valueof convierte un string 
        //en su equivalente numérico
        operando1 = Double.valueOf(pantalla.getText());
        //reseteo la pantalla
        pantalla.setText("0");
    }//GEN-LAST:event_sumaActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        double operando2 = Double.valueOf(pantalla.getText());
        if (operacion.equalsIgnoreCase("+")){
            operando1 = operando1 + operando2;
        }
        pantalla.setText(""+operando1);
    }//GEN-LAST:event_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton03;
    private javax.swing.JButton boton04;
    private javax.swing.JButton boton05;
    private javax.swing.JButton boton06;
    private javax.swing.JButton boton07;
    private javax.swing.JButton boton08;
    private javax.swing.JButton boton09;
    private javax.swing.JButton igual;
    private javax.swing.JLabel pantalla;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
}
